ENV:
  ENV_NAME: DoubleIntegratorEnv
  TIMESTEP: 0.1

VALUE_NET:
    LR: 0.001
    FEATURES:
        - 16
        - 16
        - 8
TRAIN:
  ALGO_NAME: Residual
  ITERATIONS: 1000000
  DATASET_SIZE: 1024
  BATCH_SIZE: 128
  UPDATE_TARGET_NET_EVERY_N_EPOCHS: 1

USOLVER:
  USOLVER_NAME: QuadraticSolver

LOG:
  LOG_DIR: ./logs
  LOG_EVERY_N_EPOCHS: 10
  EVAL_EVERY_N_EPOCHS: 500000
  EVAL_ACROSS_N_RUNS: 1 # for deterministic evaluation
  ANIMATE: true
