ENV:
  ENV_NAME: "PendulumEnv"
  TIMESTEP: 0.05

VALUE_NET:
    LR: 0.00001
    FEATURES:
        - 16
        - 16
        - 16
        - 16
        - 8
TRAIN:
  EPOCHS: 100000
  DATASET_SIZE: 512
  BATCH_SIZE: 128

LOG:
  LOG_DIR: "./logs"
  LOG_EVERY_N_EPOCHS: 100
