ENV:
  ENV_NAME: "PendulumEnv"
  TIMESTEP: 0.01

VALUE_NET:
    LR: 0.000003
    FEATURES:
        - 16
        - 16
        - 16
        - 16
        - 8
TRAIN:
  ALGO_NAME: "DPcFVI"
  ITERATIONS: 100000
  DATASET_SIZE: 2048
  BATCH_SIZE: 128
  N_PARALLEL_ROLLOUTS: 32
  UPDATE_TARGET_NET_EVERY_N_EPOCHS: 10

LOG:
  LOG_DIR: "./logs"
  LOG_EVERY_N_EPOCHS: 10
