ENV:
  ENV_NAME: PendulumEnv
  TIMESTEP: 0.05

VALUE_NET:
    LR: 0.0001
    FEATURES:
        - 32
        - 16
        - 16
        - 16
        - 8
TRAIN:
  ALGO_NAME: DPcFVI
  ITERATIONS: 100000
  GAMMA: 0.98
  GREEDY_EPSILON: 0.8 # RTDPcFVI
  DATASET_SIZE: 2048
  BATCH_SIZE: 256
  N_PARALLEL_ROLLOUTS: 32 # RTDPcFVI
  UPDATE_TARGET_NET_EVERY_N_EPOCHS: 2

LOG:
  LOG_DIR: ./logs
  EVAL_EVERY_N_EPOCHS: 1000
  LOG_EVERY_N_EPOCHS: 10
  EVAL_ACROSS_N_RUNS: 1 # for deterministic evaluation
  ANIMATE: true
