ENV:
  ENV_NAME: PendulumEnv
  TIMESTEP: 0.01

VALUE_NET:
    LR: 0.00005
    FEATURES:
        - 32
        - 16
        - 16
        - 16
        - 8
TRAIN:
  ALGO_NAME: DPcFVI
  ITERATIONS: 100000
  DATASET_SIZE: 2048
  BATCH_SIZE: 256
  N_PARALLEL_ROLLOUTS: 32 # for RTDPcFVI
  UPDATE_TARGET_NET_EVERY_N_EPOCHS: 1

LOG:
  LOG_DIR: ./logs
  LOG_EVERY_N_EPOCHS: 10
  EVAL_ACROSS_N_RUNS: 1 # for deterministic evaluation
